CREATE DATABASE Castello_ExtensaoVS
    DEFAULT CHARACTER SET = 'utf8mb4';

-- usar database
USE Castello_ExtensaoVS;
-- visualizar tabelas no meu banco de dados
SHOW TABLES;

-- visualizar todos os bancos de dados
SHOW SCHEMAS;

-- CRIAR TABELAS
CREATE TABLE IF NOT EXISTS ALUNOS (
    ID_CLIENTE BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF CHAR(14) NOT NULL UNIQUE,
    TELEFONE CHAR(15),
    DATA_NASCIMENTO DATETIME,
    STATUS ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO',
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);