-- SMARTCOFFEE BASE DE DADOS - DML
-- EXECUTE SEMPRE QUE QUISER RESTAURAR A AULA

DROP DATABASE IF EXISTS SMARTCOFFEE_DML_VINICIUS; 
CREATE DATABASE SMARTCOFFEE_DML_VINICIUS; 
USE SMARTCOFFEE_DML_VINICIUS; 

-- TABELAS 
CREATE TABLE CLIENTE ( 
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    NOME VARCHAR(100) NOT NULL, 
    EMAIL VARCHAR(120) NOT NULL, 
    TELEFONE VARCHAR(15),
    CIDADE VARCHAR(60) NOT NULL, 
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE, 
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
); 

CREATE TABLE CATEGORIA ( 
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT, 
    NOME_CATEGORIA VARCHAR(60) NOT NULL UNIQUE 
); 

CREATE TABLE PRODUTO (
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT, 
    NOME_PRODUTO VARCHAR(100) NOT NULL, 
    PRECO DECIMAL(10,2) NOT NULL, 
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE, 
    ID_CATEGORIA INT NOT NULL, 
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA) 
);

CREATE TABLE PEDIDO ( 
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT, 
    DATA_PEDIDO DATETIME NOT NULL, 
    STATUS_PEDIDO ENUM('ABERTO', 'PREPARANDO', 'FINALIZADO', 'CANCELADO') NOT NULL, 
    VALOR_TOTAL DECIMAL(10,2) NOT NULL DEFAULT 0.00, 
    ID_CLIENTE INT NOT NULL, 
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) 
); 

CREATE TABLE ITEM_PEDIDO ( 
    ID_ITEM INT PRIMARY KEY AUTO_INCREMENT, 
    ID_PEDIDO INT NOT NULL, 
    ID_PRODUTO INT NOT NULL, 
    QUANTIDADE INT NOT NULL, 
    PRECO_UNITARIO DECIMAL(10,2) NOT NULL, 
    OBSERVACAO VARCHAR(150), 
    CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO), 
    CONSTRAINT FK_ITEM_PEDIDO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO) 
); 

CREATE TABLE FORMA_PAGAMENTO ( 
    ID_FORMA_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT, 
    DESCRICAO VARCHAR(40) NOT NULL UNIQUE 
); 

CREATE TABLE PAGAMENTO ( 
    ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT, 
    ID_PEDIDO INT NOT NULL, 
    ID_FORMA_PAGAMENTO INT NOT NULL, 
    VALOR DECIMAL(10,2) NOT NULL, 
    DATA_PAGAMENTO DATETIME, 
    CONSTRAINT FK_PAGAMENTO_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO), 
    CONSTRAINT FK_PAGAMENTO_FORMA FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO) 
);

-- INSERCAO DE DADOS

INSERT INTO CLIENTE (NOME, EMAIL, TELEFONE, CIDADE, ATIVO) VALUES
    ('ANA SILVA', 'ANA.SILVA@email.com', '11999999001', 'São Paulo', TRUE),
    ('FELIPE VIEIRA', 'FELIPE.VIEIRA@email.com', '11999999002', 'São Paulo', TRUE),
    ('BRUNA GOMES', 'BRUNA.GOMES@email.com', '11999999003', 'AMERICANA', TRUE),
    ('MATHEUS OLIVEIRA', 'MATHEUS.OLIVEIRA@email.com', '11999999004', 'São Paulo', TRUE),
    ('CARLOS SOUZA', 'CARLOS.SOUZA@email.com', '11999999005', 'LIMEIRA', TRUE),
    ('EDUARDA CARVALHO', 'EDUARDA.CARVALHO@email.com', '11999999006', 'RIO CLARO', TRUE),
    ('VINICIUS HENRIQUE', 'VINICIUS.HENRIQUE@email.com', '11999999007', 'PIRACICABA', TRUE),
    ('GUSTAVO ASSIS', 'GUSTAVO.ASSIS@email.com', '11999999008', 'LIMEIRA', TRUE);

INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES
    ('CAFÉ'),
    ('BEBIDAS QUENTES'),
    ('BEBIDAS GELADAS'),
    ('SOBREMESAS'),
    ('LANCHES'),
    ('SANDUICHES'),
    ('SALGADOS'),
    ('DOCES');

INSERT INTO PRODUTO (NOME_PRODUTO, PRECO, ATIVO, ID_CATEGORIA) VALUES
    ('CAFÉ ESPRESSO', 5.00, TRUE, 1),
    ('CAPPUCCINO', 8.00, TRUE, 2),
    ('LATTE', 7.50, TRUE, 2),
    ('CHOCOLATE QUENTE', 6.50, TRUE, 2),
    ('CHÁ PRETO', 4.00, TRUE, 2),
    ('REFRIGERANTE LATA', 5.00, TRUE, 3),
    ('SUCO NATURAL', 7.00, TRUE, 3),
    ('ÁGUA MINERAL', 3.00, TRUE, 3),
    ('TORTA DE LIMÃO', 10.00, TRUE, 4),
    ('BOLO DE CHOCOLATE', 12.00, TRUE, 4),
    ('CHEESECAKE', 11.00, TRUE, 4),
    ('SANDUÍCHE NATURAL', 9.00, TRUE, 5),
    ('SANDUÍCHE DE FRANGO', 10.00, TRUE, 5),
    ('SANDUÍCHE DE PRESUNTO E QUEIJO', 8.50, TRUE, 5);

INSERT INTO PEDIDO (DATA_PEDIDO, STATUS_PEDIDO, VALOR_TOTAL, ID_CLIENTE) VALUES
    ('2024-06-01 10:30:00', 'ABERTO', 16.50, 1), -- Ajustado para bater com os itens
    ('2024-06-01 11:00:00', 'PREPARANDO', 8.00, 2),  -- Ajustado para bater com os itens
    ('2024-06-01 11:15:00', 'FINALIZADO', 19.00, 3), -- Ajustado para bater com os itens
    ('2024-06-01 12:00:00', 'CANCELADO', 15.00, 4),  -- Ajustado para bater com os itens
    ('2024-06-01 12:30:00', 'ABERTO', 7.00, 5),   -- Ajustado para bater com os itens
    ('2024-06-01 13:00:00', 'PREPARANDO', 6.00, 6),  -- Ajustado para bater com os itens
    ('2024-06-01 13:30:00', 'FINALIZADO', 10.00, 7), -- Ajustado para bater com os itens
    ('2024-06-01 14:00:00', 'CANCELADO', 24.00, 8),  -- Ajustado para bater com os itens
    (NOW(), 'ABERTO', 0.00, 8);

INSERT INTO ITEM_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, PRECO_UNITARIO, OBSERVACAO) VALUES
    (1, 1, 2, 5.00, 'Sem açúcar'),
    (1, 4, 1, 6.50, NULL),
    (2, 2, 1, 8.00, 'Com canela'),
    (3, 3, 2, 7.50, NULL),
    (3, 5, 1, 4.00, 'Bem passado'),
    (4, 6, 3, 5.00, NULL),
    (5, 7, 1, 7.00, 'Sem maionese'),
    (6, 8, 2, 3.00, NULL),
    (7, 9, 1, 10.00, 'Sem cobertura'),
    (8, 10, 2, 12.00, NULL);

INSERT INTO FORMA_PAGAMENTO (DESCRICAO) VALUES
    ('DINHEIRO'),
    ('CARTÃO DE CRÉDITO'),
    ('CARTÃO DE DÉBITO'),
    ('PIX');

INSERT INTO PAGAMENTO (ID_PEDIDO, ID_FORMA_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES
    (3, 1, 19.00, '2024-06-01 11:20:00'),
    (7, 2, 10.00, '2024-06-01 13:40:00'),
    (5, 3, 7.00, '2024-06-01 12:45:00'),
    (6, 4, 6.00, NOW()),
    (1, 1, 16.50, '2024-06-01 10:45:00'),
    (2, 2, 8.00, NOW());

-- UPDATE OU ATUALIZAÇÕES DE DADOS
UPDATE CLIENTE SET TELEFONE = '11999999009' WHERE ID_CLIENTE = 1;
UPDATE CLIENTE SET TELEFONE = '11999999010', CIDADE = 'CAMPINAS' WHERE ID_CLIENTE = 2;
UPDATE CLIENTE SET TELEFONE = '11999999011', CIDADE = 'SAO PAULO' WHERE ID_CLIENTE = 4;

-- ATUALIZANDO VARIOS REGISTROS
UPDATE PRODUTO SET PRECO = PRECO * 1.05 WHERE ID_CATEGORIA = 1;

-- ATUALIZANDO CONDICIONAIS
UPDATE PRODUTO
SET PRECO = CASE
    WHEN PRECO < 10 THEN PRECO * 1.10
    ELSE PRECO * 1.05
END
WHERE ATIVO = TRUE;

-- ATUALIZANDO PARA NULL
UPDATE CLIENTE SET TELEFONE = NULL WHERE ID_CLIENTE = 3;

-- EXCLUIR REGISTROS COM ESTRUTURA LÓGICA (Removido o DELETE físico do ID 8 e o TRUNCATE)
UPDATE PRODUTO SET ATIVO = FALSE WHERE ID_PRODUTO = 14;
UPDATE CLIENTE SET ATIVO = FALSE WHERE ID_CLIENTE = 8;

SELECT 'BANCO DE DADOS SMARTCOFFEE_DML_VINICIUS CRIADO COM SUCESSO!' AS MENSAGEM;
